logging:
  level:
    org:
      #springframework.data: DEBUG
      #springframework.rest: DEBUG

spring:
  data:
    mongodb:
#      username: root
#      password: root
      #username: mongouser
      #password: mongouser
      #database: ecommerce
      #port: 27017
     # host: 192.168.1.5
      #host: cluster0.tfzit.mongodb.net
      uri: mongodb+srv://mongouser:mongouser@cluster0.tfzit.mongodb.net/ecommerce?retryWrites=true&w=majority


